[package]
name = "rust-wopr"
version = "0.1.0"
authors = ["John Behan <behanj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.76"

[lib]
crate-type = ["cdylib"]